---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST: udapeople-prod.c2srhmdbtdqc.ap-northeast-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: hanmayujirou1
    - TYPEORM_DATABASE: udapeople-prod

  roles:
    - configure-server