- name: Copy to remote
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Install Node modules
  become: true
  shell: |
      cd /home/ubuntu/backend
      ls
      npm install

- name: Starting backend service
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
    npm run migrations
    cd dist
    pm2 start main.js -f